build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:18.0.0
  amd64: ghcr.io/hassio-addons/base/amd64:18.0.0
  armhf: ghcr.io/hassio-addons/base/armhf:18.0.0
  armv7: ghcr.io/hassio-addons/base/armv7:18.0.0
  i386: ghcr.io/hassio-addons/base/i386:18.0.0
labels:
  org.opencontainers.image.title: "Intelbras Solar"
  org.opencontainers.image.description: "Integração com o painel da Intelbras Solar."
  org.opencontainers.image.source: "https://github.com/mastria/hassio-addons/tree/main/intelbras-solar"
  org.opencontainers.image.licenses: "MIT"
codenotary:
  signer: codenotary@frenck.dev
